# Generated by Django 2.2.4 on 2019-08-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='fps',
            field=models.IntegerField(default=0),
        ),
    ]
