# Generated by Django 2.2.4 on 2019-08-26 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_auto_20190826_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Trans',
        ),
    ]
