# Generated by Django 2.2.4 on 2019-08-27 00:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0003_auto_20190826_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trans',
            new_name='Car',
        ),
    ]
