# Generated by Django 2.2.4 on 2019-08-27 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0004_auto_20190827_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicle',
        ),
    ]
