# Generated by Django 2.2.4 on 2019-08-28 06:39

from django.db import migrations, models

def defaults(apps, schema_editor):
    System = apps.get_model('vehicle', 'System')
    s = System(name='full_name', value='ACD Vehicle Plate Recognition System')
    s.save()
    s = System(name='short_name', value='ACD-VPR-SYS')
    s.save()
    s = System(name='mission', value='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque massa lectus, placerat eget tortor id, vehicula pharetra quam. Proin sit amet aliquam sem. Maecenas ac porta magna. Mauris posuere aliquam posuere. Ut efficitur nunc eu augue venenatis luctus. Nulla tellus turpis, molestie id faucibus et, porttitor porttitor nibh. Quisque ut laoreet tortor, nec vestibulum velit. Cras ultrices ut ligula at ultricies. Nulla est odio, sollicitudin id neque at, congue tristique felis.<br>Maecenas varius lorem sit amet est convallis auctor. Sed purus leo, luctus sit amet vestibulum et, rutrum sed purus. Sed sagittis scelerisque mi, at interdum ante malesuada at. Pellentesque faucibus consectetur suscipit. Sed eleifend mattis turpis gravida cursus. Aenean risus lectus, efficitur eget posuere sit amet, convallis a elit. Phasellus sit amet lorem a nisi cursus vulputate nec sit amet mi. Interdum et malesuada fames ac ante ipsum primis in faucibus.')
    s.save()
    s = System(name='vision', value='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra ante eget urna tincidunt, et pharetra ligula aliquet. Praesent vitae enim urna. Nulla id tortor ipsum. Curabitur mattis lectus ac nisi lobortis consectetur. Integer at justo non mi iaculis finibus ut a turpis. Ut auctor tortor nunc, ut bibendum augue lacinia et. Nulla facilisi.<br>Maecenas nunc nunc, lacinia ut vehicula eu, dapibus a ex. Aenean pretium euismod tristique. Nullam sit amet volutpat dui. Morbi finibus nec ipsum ut sollicitudin. Pellentesque luctus ante placerat nibh elementum, porttitor pharetra enim suscipit. Mauris ut massa a dui scelerisque scelerisque quis sit amet ante. Sed convallis sed augue nec posuere. Quisque eleifend mollis lorem. Maecenas lacinia diam nunc, sed pulvinar est elementum sit amet. Duis scelerisque pretium neque, in luctus felis cursus at. Suspendisse gravida auctor sagittis. Fusce id purus nisi. Quisque euismod orci massa.')
    s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20190827_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
    ]
