# Generated by Django 2.2.4 on 2019-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20190828_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime_out',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
