# Generated by Django 2.2.4 on 2019-08-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20190828_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.IntegerField(default=1, max_length=11),
        ),
    ]
