# Generated by Django 2.2.4 on 2019-08-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
