# Generated by Django 2.2.4 on 2019-08-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20190829_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
