# Generated by Django 2.2.4 on 2019-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
