# Generated by Django 2.2.4 on 2019-09-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_log_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='edited_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
